spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: never
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    ROOT: info
server:
  servlet:
    context-path: "/api"
jwt:
  secret: "minesweeper_application"