spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: minesweeper
    password: minesweeper
    initialization-mode: never
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    ROOT: info
server:
  servlet:
    context-path: "/api"
jwt:
  secret: "minesweeper_application"

---
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: never
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    ROOT: info
server:
  servlet:
    context-path: "/api"
jwt:
  secret: "minesweeper_application"